<a href="https://colab.research.google.com/github/hps-nguyen/pytorch-deep-learning/blob/main/code_along/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Intro to Tensors

### Creating tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])

In [6]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [7]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3]],
                       [[3, 6, 9]],
                       [[2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3]],

        [[3, 6, 9]],

        [[2, 4, 5]]])

In [12]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([3, 1, 3]))

### Random tensors

In [16]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9292, 0.9284, 0.4215, 0.3534],
        [0.6817, 0.7612, 0.2897, 0.0753],
        [0.6244, 0.5363, 0.3178, 0.7701]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [36]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [52]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device="cpu",
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [53]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [54]:
float_16_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [56]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [57]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [59]:
print(float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device)

torch.float32 torch.Size([3]) cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [67]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [68]:
# Add 10
tensor + 10

tensor([11, 12, 13])

In [69]:
# Multiply 10
tensor * 10

tensor([10, 20, 30])

In [70]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [79]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [93]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [91]:
%%time
tensor @ tensor

CPU times: user 543 µs, sys: 0 ns, total: 543 µs
Wall time: 414 µs


tensor(14)

In [92]:
%%time
result = 0
for value in tensor:
    result += value * value
result

CPU times: user 253 µs, sys: 953 µs, total: 1.21 ms
Wall time: 911 µs


tensor(14)

In [95]:
tensor = torch.tensor([[1, 2, 3],
                       [2, 4, 6]])
tensor, tensor.shape

(tensor([[1, 2, 3],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [97]:
torch.mm(tensor, tensor.T) # (2, 3) @ (3, 2) --> (2, 2)

tensor([[14, 28],
        [28, 56]])