<a href="https://colab.research.google.com/github/hps-nguyen/pytorch-deep-learning/blob/main/code_along/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Intro to Tensors

### Creating tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])

In [6]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [7]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [9]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3]],
                       [[3, 6, 9]],
                       [[2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3]],

        [[3, 6, 9]],

        [[2, 4, 5]]])

In [10]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([3, 1, 3]))

### Random tensors

In [11]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1442, 0.8729, 0.6820, 0.4386],
        [0.5871, 0.3071, 0.7089, 0.0196],
        [0.0046, 0.8307, 0.7913, 0.8550]])

In [12]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [13]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
ones.dtype

torch.float32

In [16]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [17]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [19]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device="cpu",
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [20]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
float_16_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [22]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [23]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [24]:
print(float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device)

torch.float32 torch.Size([3]) cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [25]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [26]:
# Add 10
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [29]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [30]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
%%time
tensor @ tensor

CPU times: user 63 µs, sys: 9 µs, total: 72 µs
Wall time: 75.3 µs


tensor(14)

In [32]:
%%time
result = 0
for value in tensor:
    result += value * value
result

CPU times: user 283 µs, sys: 37 µs, total: 320 µs
Wall time: 329 µs


tensor(14)

In [33]:
tensor = torch.tensor([[1, 2, 3],
                       [2, 4, 6]])
tensor, tensor.shape

(tensor([[1, 2, 3],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [34]:
torch.mm(tensor, tensor.T) # (2, 3) @ (3, 2) --> (2, 2)

tensor([[14, 28],
        [28, 56]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [35]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [36]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [38]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

`torch.mean()` only works for float or complex dtype input.

## Finding the positional min and max

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
# Find the argmin
x.argmin()

tensor(0)

In [41]:
# Find the argmax
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshape: reshape an input tensor to a defined shape
* View: return a view of an input tensor of certain shape but keep the same memory
* Stack: combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: remove all `1` dimensions from a tensor
* Unsqueeze: add a `1` dimension to a target tensor
* Permute: return a view of the input with dimensions permuted (swapped) in a certain way

In [42]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [43]:
# Add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 2)

In [44]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing `z` changes `x` (because a view of a tensor shares the same memory as the original input).

In [45]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [46]:
# Squeeze (torch.squeeze() removes all single dimensions from a target tensor)
x_reshaped = x_reshaped.reshape(1, 9)

# Before squeezing
print(f'Before squeezing:\n {x_reshaped}, shape: {x_reshaped.shape}')
# After squeezing
print(f'After squeezing:\n {x_reshaped.squeeze()}, shape: {x_reshaped.squeeze().shape}')

Before squeezing:
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), shape: torch.Size([1, 9])
After squeezing:
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), shape: torch.Size([9])


In [47]:
x_squeezed = x_reshaped.squeeze()

# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
# Permute
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

`x_permuted` is a view of `x_original`.

## PyTorch tensors & NumPy

In [49]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Going from NumPy to PyTorch, the default dtype in NumPy is `float64`.

In [50]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In [51]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [52]:
# Make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

### 1. Getting a GPU

In [53]:
!nvidia-smi

Mon Apr 14 03:39:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   75C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [54]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [55]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [56]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Puttting tensors (and models) on the GPU

In [57]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [58]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

**Note**: If tensor is on GPU, we can't transform it to NumPy. So to fix the GPU tensor with NumPy issue, we can first set it to the CPU.

In [59]:
tensor_to_array = tensor_on_gpu.cpu().numpy()
tensor_to_array

array([1, 2, 3])